version: '3.8'

services:
  # EdgeX Foundry services
  edgex-redis:
    image: redis:7.0.15-alpine
    container_name: edgex-redis
    ports:
      - "6379:6379"
    networks:
      - edgex-network
    volumes:
      - edgex-redis-data:/data
    restart: unless-stopped

  edgex-core-consul:
    image: hashicorp/consul:1.16.6
    container_name: edgex-core-consul
    command: ["agent", "-ui", "-bootstrap", "-server", "-client", "0.0.0.0"]
    ports:
      - "8500:8500"
    networks:
      - edgex-network
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: root:root
    volumes:
      - ./consul/config:/consul/config
      - ./consul/data:/consul/data

  edgex-core-common-config-bootstrapper:
    image: edgexfoundry/core-common-config-bootstrapper:3.1.1
    container_name: edgex-core-common-config-bootstrapper
    depends_on:
      - edgex-core-consul
    environment:
      ALL_SERVICES_DATABASE_HOST: edgex-redis
      ALL_SERVICES_MESSAGEBUS_HOST: edgex-redis
      ALL_SERVICES_REGISTRY_HOST: edgex-core-consul
      APP_SERVICES_CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      DEVICE_SERVICES_CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      EDGEX_SECURITY_SECRET_STORE: "false"
    networks:
      - edgex-network
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
    volumes:
      - /etc/localtime:/etc/localtime:ro

  edgex-core-metadata:
    image: edgexfoundry/core-metadata:3.1.1
    container_name: edgex-core-metadata
    depends_on:
      - edgex-redis
    ports:
      - "59881:59881"
    environment:
      - EDGEX_SECURITY_SECRET_STORE=false
      - SECRETSTORE_TOKENFILE=/tmp/edgex/secrets/edgex-core-metadata/secrets-token.json
      - SERVICE_HOST=edgex-core-metadata
      - CLIENTS_CORE_COMMAND_HOST=edgex-core-command
      - CLIENTS_CORE_DATA_HOST=edgex-core-data
      - CLIENTS_NOTIFICATIONS_HOST=edgex-support-notifications
      - CLIENTS_SCHEDULER_HOST=edgex-support-scheduler
      - DATABASES_PRIMARY_HOST=edgex-redis
      - REGISTRY_HOST=edgex-core-consul
    networks:
      - edgex-network
    restart: unless-stopped

  edgex-core-data:
    image: edgexfoundry/core-data:3.1.1
    container_name: edgex-core-data
    depends_on:
      - edgex-redis
      - edgex-core-metadata
    ports:
      - "59880:59880"
    environment:
      - EDGEX_SECURITY_SECRET_STORE=false
      - SECRETSTORE_TOKENFILE=/tmp/edgex/secrets/edgex-core-data/secrets-token.json
      - SERVICE_HOST=edgex-core-data
      - CLIENTS_CORE_METADATA_HOST=edgex-core-metadata
      - CLIENTS_CORE_COMMAND_HOST=edgex-core-command
      - CLIENTS_NOTIFICATIONS_HOST=edgex-support-notifications
      - CLIENTS_SCHEDULER_HOST=edgex-support-scheduler
      - DATABASES_PRIMARY_HOST=edgex-redis
      - REGISTRY_HOST=edgex-core-consul
    networks:
      - edgex-network
    restart: unless-stopped

  edgex-core-command:
    image: edgexfoundry/core-command:3.1.1
    container_name: edgex-core-command
    depends_on:
      - edgex-redis
      - edgex-core-metadata
    ports:
      - "59882:59882"
    environment:
      - EDGEX_SECURITY_SECRET_STORE=false
      - SECRETSTORE_TOKENFILE=/tmp/edgex/secrets/edgex-core-command/secrets-token.json
      - SERVICE_HOST=edgex-core-command
      - CLIENTS_CORE_METADATA_HOST=edgex-core-metadata
      - CLIENTS_CORE_DATA_HOST=edgex-core-data
      - CLIENTS_NOTIFICATIONS_HOST=edgex-support-notifications
      - CLIENTS_SCHEDULER_HOST=edgex-support-scheduler
      - DATABASES_PRIMARY_HOST=edgex-redis
      - REGISTRY_HOST=edgex-core-consul
    networks:
      - edgex-network
    restart: unless-stopped

  edgex-device-virtual:
    image: edgexfoundry/device-virtual:3.1.1
    container_name: edgex-device-virtual
    depends_on:
      - edgex-core-command
    ports:
      - "59900:59900"
    environment:
      - EDGEX_SECURITY_SECRET_STORE=false
      - SECRETSTORE_TOKENFILE=/tmp/edgex/secrets/device-virtual/secrets-token.json
      - SERVICE_HOST=edgex-device-virtual
      - CLIENTS_CORE_METADATA_HOST=edgex-core-metadata
      - CLIENTS_CORE_DATA_HOST=edgex-core-data
      - CLIENTS_CORE_COMMAND_HOST=edgex-core-command
      - DATABASES_PRIMARY_HOST=edgex-redis
      - REGISTRY_HOST=edgex-core-consul
    networks:
      - edgex-network
    restart: unless-stopped

  # ThingsBoard Edge 服务
  thingsboard-edge:
    restart: always
    image: "thingsboard/tb-edge:3.9.1EDGE"
    container_name: thingsboard-edge
    ports:
      - "8080:8080"
      - "1883:1883"
      - "5683-5688:5683-5688/udp"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tb-edge
      CLOUD_ROUTING_KEY: 1643053f-4352-1447-107e-66ff2b278529
      CLOUD_ROUTING_SECRET: d2ok76gofk3ukhpaiiwb
      CLOUD_RPC_HOST: demo.thingsboard.io
      CLOUD_RPC_PORT: 7070
      CLOUD_RPC_SSL_ENABLED: false
    volumes:
      - tb-edge-data:/data
      - tb-edge-logs:/var/log/tb-edge
    networks:
      - thingsboard-network
    depends_on:
      - postgres

  postgres:
    restart: always
    image: "postgres:16"
    container_name: postgres
    ports:
      - "5432"
    environment:
      POSTGRES_DB: tb-edge
      POSTGRES_PASSWORD: postgres
    volumes:
      - tb-edge-postgres-data:/var/lib/postgresql/data
    networks:
      - thingsboard-network

  # 小米AIoT边缘安全防护研究平台
  aiot-security-platform:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: aiot-security-platform
    ports:
      - "5000:5000"  # Web界面
      - "9090:9090"  # API接口
    environment:
      - EDGEX_METADATA_URL=http://edgex-core-metadata:59881
      - EDGEX_DATA_URL=http://edgex-core-data:59880
      - EDGEX_COMMAND_URL=http://edgex-core-command:59882
      - THINGSBOARD_URL=http://thingsboard-edge:8080
      - THINGSBOARD_MQTT_HOST=thingsboard-edge
      - THINGSBOARD_MQTT_PORT=1883
      - SIMULATION_MODE=true
      - LOG_LEVEL=INFO
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./reports:/app/reports
      - ./data:/app/data
    networks:
      - edgex-network
      - thingsboard-network
    depends_on:
      - edgex-core-metadata
      - edgex-core-data
      - edgex-core-command
      - thingsboard-edge
    restart: unless-stopped

networks:
  edgex-network:
  thingsboard-network:

volumes:
  edgex-redis-data:
  tb-edge-data:
    name: tb-edge-data
  tb-edge-logs:
    name: tb-edge-logs
  tb-edge-postgres-data:
    name: tb-edge-postgres-data