version: 1
formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: logs/security/security_events.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

root:
  level: INFO
  handlers: [console, file]
  propagate: true

loggers:
  src:
    level: DEBUG
    handlers: [console, file]
    propagate: false

  src.security:
    level: INFO
    handlers: [file]
    propagate: true

  src.dashboard:
    level: DEBUG
    handlers: [console]
    propagate: true