analytics:
  analysis:
    metrics:
    - cpu_usage
    - memory_usage
    - network_throughput
    - attack_detection_rate
    time_window: daily
  data_dir: data
  output_dir: output
  visualization:
    dpi: 300
    enabled: true
    format: png
devices:
  auto_create: true
  list:
  - name: xiaomi_gateway_01
    platform: both
    properties:
      init_connected_devices: 5
      max_connected_devices: 20
      telemetry_interval: 5
    type: gateway
  - name: xiaomi_router_01
    platform: both
    properties:
      max_bandwidth: 1000
      telemetry_interval: 5
      wifi_channels:
      - 2.4GHz
      - 5GHz
    type: router
  - name: xiaomi_speaker_01
    platform: both
    properties:
      max_bluetooth_devices: 5
      max_volume: 100
      telemetry_interval: 5
    type: smart_speaker
  - name: xiaomi_camera_01
    platform: both
    properties:
      available_resolutions:
      - 640x480
      - 1280x720
      - 1920x1080
      motion_detection: true
      night_vision: true
      telemetry_interval: 5
    type: camera
platform:
  edgex:
    api_version: v2
    auth:
      enabled: true
      token: ${EDGEX_TOKEN}
    core_command_port: 59882
    device_service_name: xiaomi-device-service
    host: localhost
    metadata_port: 59881
    port: 59880
  thingsboard:
    auth:
      password: wlsxcdh52jy.L
      token: ${eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ5eTMyMDU1NDM4MDhAZ21haWwuY29tIiwidXNlcklkIjoiNjk2ZGE4MDAtMTYwZi0xMWYwLTg3MWItZWQxMjZmYmFkMGVlIiwic2NvcGVzIjpbIlRFTkFOVF9BRE1JTiJdLCJzZXNzaW9uSWQiOiI4YzNlNjFjNi04ODQ2LTQyOWMtYmJkMy05OTAyODA2YzdmNWEiLCJleHAiOjE3NDY0OTcxNDEsImlzcyI6InRoaW5nc2JvYXJkLmlvIiwiaWF0IjoxNzQ0Njk3MTQxLCJlbmFibGVkIjp0cnVlLCJpc1B1YmxpYyI6ZmFsc2UsInRlbmFudElkIjoiNjdiMDhlYjAtMTYwZi0xMWYwLTg3MWItZWQxMjZmYmFkMGVlIiwiY3VzdG9tZXJJZCI6IjEzODE0MDAwLTFkZDItMTFiMi04MDgwLTgwODA4MDgwODA4MCJ9.1iOj-HLW18i56yQZJa_xCIv6_NgTg6c4hslokMegEDHH2Qyps4qi_73K6HiN2brQxUbgDzaAZBzEfPHjWKK66g
      username: yy3205543808@gmail.com
    host: localhost
    mqtt_port: 1883
    port: 8080
    reconnect:
      interval: 30
      max_retries: 10
    security:
      cert_file: certs/client.crt
      key_file: certs/client.key
      ssl_verify: true
    ws_url: wss://localhost:8080/ws
security:
  attack_simulator:
    attacks_enabled:
      credential: true
      data_exfiltration: true
      ddos: true
      firmware: true
      iot_botnet: true
      mitm: true
      physical_tampering: true
      protocol: true
    intensity: medium
    simulation_interval: 30
  distributed: true
  nodes:
  - network:
      discovery_port: 5556
      host: 127.0.0.1
      port: 5555
    node_id: security_node_coordinator
    node_type: coordinator
    roles:
    - detector
    - protector
    - logger
  - associated_devices:
    - xiaomi_gateway_01
    network:
      coordinator: 127.0.0.1:5555
    node_id: security_node_gateway
    node_type: worker
    roles:
    - detector
    - protector
  - associated_devices:
    - xiaomi_router_01
    network:
      coordinator: 127.0.0.1:5555
    node_id: security_node_router
    node_type: worker
    roles:
    - detector
