{
    "web_port": 5000,
    "log_dir": "data/attack_logs",
    "capture_dir": "data/packet_capture",
    "attack_log_retention_days": 30,
    "packet_capture_limit": 100,
    "refresh_interval": 5,
    "enable_packet_capture": true
}